### ISSUE TITLE
Photos UI

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#101]
I removed the photo icon from the home page (see issue #98) and want to instead rely on menu access for adding photos to the Boswell "library". 
- Change the title and add the indicated explanatory text on the photos window. See attached. 
- When press-holding on a photo, a pop-up menu asks: 
- "Remove from Boswell" (with a red X), or
- Cancel

We will add other menu items there in the future (eg. "Ask about this photo again")

Note: my plan is to have Boswell randomly ask about a photo (every 3-5 questions) and make it the background during that questioning. "What is this picture about?  When was it taken?  Where?...". So we will eventually want to put a "check mark" on photos that have been talked about already.

![image](https://github.com/tedbarnett/Boswell/assets/694013/1e52d011-4cfc-4700-b7db-492cba8469ba)

**Comment by tedbarnett** [comment]
Typos: 
1. Title of Photo page should be "Photo Memories" (not Background)
2. The text at the bottom: first sentence should read 'Add photos with the "+" icon.' (i.e. "the", not "then")

**Comment by tedbarnett** [comment]
Let's eliminate the "Alert" dialog that shows up when user deletes a photo.  Users can easily add them back, so not a big deal if deleted.  No need to confirm that choice.

**Comment by tedbarnett** [comment]
When use goes to add photos ("+"), eliminate the "Show Selected" item at the bottom.  Leave the "Select up to 10 photos" (for now).

And make the "Add" link at the top right blue (so that it looks clickable)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  we can't eliminate the "Show Selected" item at the bottom it's ios default behaviour. same for the "add" link. The "Add" button is disabled until select a photo

**Comment by tedbarnett** [comment]
Okay.  Let's go with what we have then.  It's working!
