### ISSUE TITLE
Simplify Font dialog

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#105]
The font dialog box is too large and messy
- Change font size to a simple pop-up list (10, 12, 14, 16,..., 24)
- move the color choice to the right of the font size (ie just the color circle: tap it to change color, no label)
- Font weight should become a simple Bold/normal pop/up list
- make the dialog box as compact and efficient as possible!

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I have created a sample design for the font dialogue. here is a sketch file screenshot please check it and let me know.

![iPhone 13 Pro](https://github.com/tedbarnett/Boswell/assets/114083934/7e99654a-33bc-4744-b897-4011504bc9e9)

**Comment by tedbarnett** [comment]
Nice. Any way to make the color choice a circle (as you have here)? It shows up as a square on my build.

---
***@***.***
https://www.linkedin.com/in/tedbarnett
