### ISSUE TITLE
Disable storing Eleven Labs responses in ElevenLabs.ai "History"

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#109]
Right now, every time we use the Eleven Labs API to generate a new phrase for Boswell, it is adding that voice audio to the "history" listing on my Eleven Labs account.   I don't need these and they are cluttering up my interface there.  Perhaps there is a flag we can set that will keep it from storing the audio at Eleven Labs?

https://api.elevenlabs.io/docs#/history/Delete_history_item_v1_history__history_item_id__delete

![image](https://github.com/tedbarnett/Boswell/assets/694013/66deb0b6-bc46-475a-964f-cc22c9462860)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I have reviewed the API documentation of Eleven Labs and it does not include a flag or option to disable the "save to history" feature. However, we can implement an alternative approach. Upon opening the app, we can retrieve the history from Eleven Labs and proceed to delete each individual history entry in the background.

**Comment by tedbarnett** [comment]
Can you just get each new history item and delete that one?  I don't want to lose some of the experiments I'm running myself.

**Comment by tedbarnett** [comment]
Not a priority yet.  I will hand-delete the old audio for now.
