### ISSUE TITLE
Fix TextView so not clickable

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#11]
Currently, if the user taps anywhere in the TextView area, the keyboard appears though user cannot edit the text. Prevent this!

**Comment by prempratapsingh** [comment]
hey @tedbarnett , I am starting to work on this issue.

**Comment by prempratapsingh** [comment]
Layout constraints (https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithConstraintsinInterfaceBuidler.html) has not been defined for the text view and other view elements which may be causing this issue. I am setting up the layout constraints.

<img width="1121" alt="Screenshot 2023-04-17 at 4 45 36 PM" src="https://user-images.githubusercontent.com/27926337/232469480-33d7c2cf-5294-4305-888a-a729a0d38295.png">

**Comment by prempratapsingh** [comment]
I added the required constraints (alignment, padding, spacing, etc) and UI properties like border for text view to show text input area, clear button title, rounded corner to the record button to make the UI look like standard iOS app UI.

Here is how the UI now looks on iPhone SE,

<img width="434" alt="Screenshot 2023-04-17 at 5 12 43 PM" src="https://user-images.githubusercontent.com/27926337/232474814-7c5c227f-f69b-423a-8aed-b9bc9e7ed367.png">

It was looking like this before,
<img width="428" alt="Screenshot 2023-04-17 at 4 41 59 PM" src="https://user-images.githubusercontent.com/27926337/232474852-427231c0-dba4-4c87-8663-6b6a35830f80.png">

**Comment by prempratapsingh** [comment]
UI is looking better on larger screens (iPhone 14 Pro) as well.

<img width="250" alt="Screenshot 2023-04-17 at 5 12 21 PM" src="https://user-images.githubusercontent.com/27926337/232475208-39622bc6-c7b8-48f9-a102-69f988048681.png">

It was looking like this on large screen before,

<img width="250" alt="Screenshot 2023-04-17 at 4 43 01 PM" src="https://user-images.githubusercontent.com/27926337/232475298-f3533a5d-f8da-4460-be2c-4d23632bfcd2.png">

**Comment by tedbarnett** [comment]
[bhautikpatoliya004](https://github.com/bhautikpatoliya004) fixed the main issue (now checked into main), but I'd like to get [prempratapsingh](https://github.com/prempratapsingh)'s improvements rolled in too.  Like the larger button, scalable UI.  Want to keep the current text color scheme (in main now).
