### ISSUE TITLE
Audio levels too low on iPhone

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#12]
Currently, on an iPhone 14 Pro running iOS 16, the first text-to-speech audio played out through the speaker.  But subsequent audio played through the headset speaker, at a very low volume.  This does not occur in the Xcode iPhone 14 simulator (i.e. it works properly there).  Preferred behavior is that all audio comes out of the Speaker on the iPhone (or iPad) at high volume.

Note: code related to Eleven Labs is expected to replace appleSpeak function eventually. Do not delete this part of the code.

**Comment by HuongPlc** [comment]
Hi. So i have exp in AVFoundation and chatGPT and also have over 5 YoE in iOS. I see your job post in upwork. Can we chat with detail?

**Comment by tedbarnett** [comment]
Seems to work now on my iPhone 14 Pro.  Awesome!  
Could you leave a comment as to how you fixed this in the future?  Or put a comment in the code explaining the change?
