### ISSUE TITLE
Stop Recording if User pauses speaking for more than n seconds

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#122]
I want older folks to be able to use Boswell. I'd like to make it work without pressing any buttons, ideally. 

But for now let's just time out gracefully if the user is silent for more than N seconds. Set N to 10 seconds to start.  Act as if the user pressed the Stop recording button.

**Comment by tedbarnett** [comment]
In other words, if I pause for more than 10 seconds while speaking, Boswell will assume I have finished talking and press the "Stop Recording" button for me, then provide its response.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Right now I'm checking the audio level if the audio level is less than 0.1 (silenceThreshold is a variable name in the code) then consider silence. if we got silence for 10 seconds then stop recording. 

let me set silenceThreshold = 0.01. You can also update this silenceThreshold value for your testing.
