### ISSUE TITLE
Photo appearing without a photo question

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#144]
Twice today, I have seen a photo appear when Boswell is asking an "interviewStart" question.  I can't tell why.  The photo appears and stays until the next question is asked, but it is not asked about.  Not sure how to reliably recreate this.  Do you see it too?

Here are two examples.  Note that the first one appeared when I returned to Boswell after switching to ChatGPT mode and back again.  See how it ignored the original question ("when you were 21") and added a second question even though I had not answered the first.  Don't know if that's related.

![68B7E23C-F426-40AB-8A24-2409E17B047D](https://github.com/tedbarnett/Boswell/assets/694013/34ec6bae-349c-4af5-b2aa-5ff20a668964)

![79020441-ACC1-46B2-84C8-9B355876F828](https://github.com/tedbarnett/Boswell/assets/694013/8df325e1-d0f3-4aab-835d-93f49d28c808)

**Comment by tedbarnett** [comment]
I've only seen this happen for a "first" question (either starting up Boswell) or returning to it from another app.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I have tested it on my end I never reproduce this issue. but I'm sure it's happening because AI returns this '-*---photo-question:nnnnn' pattern in response even if the question is not related to photos.

**Comment by tedbarnett** [comment]
Can you write the responses to the terminal window/log so that I can see this?
