### ISSUE TITLE
Ensure working on Apple TV

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#17]
This app should work on the Apple TV too.  Has a mic and speaker, runs iOS now. 
Goal: Boswell runs on latest Apple TV model, mic via remote?

**Comment by tedbarnett** [comment]
I'd really like to see this work on an AppleTV.  Any reason it would not?  I know the Watch did not work out easily, but to me this is more important since older folks (e.g. my parents) are using an AppleTV and could answer questions together.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett 
The TV app is the same as a watch app. tvOS is derived from iOS but is a distinct OS, including some frameworks that are supported only on tvOS. so for the tvOS app, we need to create a separate target for this app means creating a separate app for tvOS and sharing some code between iOS and tvOS apps.

our current UI is in the storyboard and .xib file so it's not supported by tvOS we need to create a separate UI for the tvOS app. We can share code between apps but we can't share saved settings and files between these two devices without a server. Please let me know if we need to start work on it

**Comment by tedbarnett** [comment]
Understood.  Let's leave this for a v2.0 some day.  I will close as not-fixable for now...
