### ISSUE TITLE
Enable Switching Between GPT-3.5-turbo and GPT-4

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#19]
Set up the code so that the user can change the API Model between GPT-3.5-turbo and GPT-4.   Users might want to avoid excessive costs using GPT-4 sometimes!

The UI for this will appear in the Menu.  See[ Issue #9](https://github.com/tedbarnett/Boswell/issues/9)

**Comment by bhautikpatoliya004** [comment]
You can check APIManager.swift line no 35.
If we got a saved model GPT-4 then we update the request URL and parameter for GPT-4 API call
