### ISSUE TITLE
Make font styles selectable

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#20]
Add a Menu Item called "Appearance".  Choosing it opens an Appearances settings window which lets user select: 

- Font size and color and bold/normal for User prompts (i.e. what the user says or types)
- Font size and color and bold/normal for AI Response (i.e. what OpenAI responds with)

**Comment by tedbarnett** [comment]
Could you display the text "Sample prompt" next to the Font color  for User prompts and "Sample AI" for AI Reponse?  And have that text change to whatever settings the user chooses?  I want them to be able to see what the text will look like when changed.

**Comment by bhautikpatoliya004** [comment]
Done

**Comment by tedbarnett** [comment]
Well done.
