### ISSUE TITLE
Mute AI Response Audio Immediately if Sound Menu set to Off

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#26]
Currently, if the AI is speaking, and the user opens the menu and turns off sound, the audio does not go to mute immediately. Ideally, the audio would immediately mute.  It would not wait to mute the next response.

**Comment by bhautikpatoliya004** [comment]
There is no direct way to immediately mute the sound. so I have stored the current speech's full text in the currentSpeechText variable and the last spoken text range in the spokenTextRange variable. Then stop the speech immediately when the sound setting changes and then start the speech again with new sound settings from the last stop based on  currentSpeechText and spokenTextRange variables.

ViewController+SpeechDelegate.swift check didFinish method.

**Comment by tedbarnett** [comment]
Fix seems to work well!
