### ISSUE TITLE
Improve text spacing

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#28]
Line spacing after the user prompt is inconsistent. Currently, the AI response appears either after several blank lines or after a single space (see attached screenshot). 

The preferred behavior would be: AI response appears on the very next line after the user prompt. Also, a blank line should be generated after the AI response (before the next user prompt).

TextView should look like this:

**User prompt here**
AI response here

**User prompt here**
AI response here

----
Current behavior:

![image](https://user-images.githubusercontent.com/694013/232892103-060351ad-ea77-40ec-b45c-971e0d63d5aa.jpeg)

**Comment by bhautikpatoliya004** [comment]
Fixed
