### ISSUE TITLE
Improve default font appearance

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#29]
The default font settings should be set as follows (for new users):

![image](https://user-images.githubusercontent.com/694013/232891719-bd6ecf0d-f4ce-4160-aacb-c961950dc06b.jpeg)Image here

**Comment by bhautikpatoliya004** [comment]
Done. but still, you can change the default appearance from Constant.swift (DeafultFontAppearance)

**Comment by tedbarnett** [comment]
Fixed!
