### ISSUE TITLE
Remember Chat History

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#30]
Until a user chooses "New Chat", the AI should remember all of the prior conversation history. This is how the ChatGPT web app works (see attached). 
![image](https://user-images.githubusercontent.com/694013/232893205-71144455-0b7a-434d-aac4-f85b3dd79f28.png)

Our app seems to have no memory at all (see below).
![image](https://user-images.githubusercontent.com/694013/232893278-ff12b3a7-3141-4237-ac44-0caa6b211e6c.png)

I believe there is a way to fix this. It may require that we prepend the full chat history to the beginning of every prompt that we submit.  I asked ChatGPT-4 how to fix this and got the following reply:

----
**If I am building a chat application using GPT4 how do I ensure that the system remembers prior prompts and responses?**

When building a chat application with GPT-4, you can ensure that the system remembers prior prompts and responses by maintaining a conversation history. Here's a high-level overview of how you can achieve this:

1. Store conversation history: Maintain a data structure, such as a list, to store the conversation history. This should include both user inputs and the AI's responses.

2. Concatenate messages: Before sending a new user input to GPT-4, concatenate the conversation history into a single string. This can be done by alternating user messages and AI responses, and separating them with suitable tokens or delimiters. For example:
`User: How's the weather today?
AI: The weather is sunny and warm.
User: What's the temperature?`

3. Use tokens or delimiters: It's important to use tokens or delimiters that are easily recognizable by GPT-4, such as special characters or tokens that indicate the role of the speaker (e.g., "User:" and "AI:"). This allows the model to understand the context and differentiate between user inputs and AI responses.

4. Limit message length: GPT-4 has a maximum token limit per input (e.g., 4096 tokens for GPT-3). Make sure the concatenated conversation string does not exceed this limit. If it does, you may need to truncate, omit, or shorten some of the text to fit within the limit. Be cautious when removing context, as this may impact the quality of the model's responses.

5. Send the concatenated string to GPT-4: Pass the concatenated string as input to the GPT-4 API. The model will process the input and generate a response based on the provided context.

6. Update conversation history: After receiving a response from GPT-4, add the response to your conversation history data structure. This will ensure the context is maintained for future interactions.

By following these steps, you can create a chat application with GPT-4 that remembers prior prompts and responses, providing a more coherent and context-aware conversational experience.

**Comment by bhautikpatoliya004** [comment]
I have created an array of chat history between You and the AI. That way AI can remember previous chat and responds to the user based on history.

APIManager.swift changed requestData for GPT-4 and gpt-3.5-turbo

**Comment by tedbarnett** [comment]
Tested and it works!
