### ISSUE TITLE
Switch audio to AirPods if connected

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#34]
Currently, the AI voice always plays through the iPhone speaker, even if my AirPods are connected and active. 

Preferred behavior: if AirPods (or other iPhone headphones) are connected, route AI response audio to the AirPods. If they are disconnected, reroute to Speaker again. 

Similarly, the microphone input should also switch to the AirPod microphone if connected.

**Comment by tedbarnett** [comment]
New issue caused by this: does not switch to iphone mic after removing Airpods

**Comment by bhautikpatoliya004** [comment]
I tested the AirPods today and they were working fine on my end. Could you also test them again and let me know the specific steps you took?

**Comment by tedbarnett** [comment]
Hmm.  It does seem to work well enough.  Perhaps it was my own Bluetooth setup here.
