### ISSUE TITLE
Layout Fixes in Landscape Mode

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#35]
The landscape mode layout for Boswell can be improved.
- Move the share icon and hamburger menu down 3-4 points (too close to top edge of screen)
- make the Boswell title 4 points larger and make sure bottom of text lines up with bottom of share icon/menu icon
- move the grey subtitle ("Your Personal Biographer") up to just under the "Boswell" title (less white space)

![image](https://user-images.githubusercontent.com/694013/233132120-e7d89606-6ba6-419b-8db6-807dd535878f.jpeg)

**Comment by bhautikpatoliya004** [comment]
I have set the title and buttons in the device navigation bar. if we changed the title size then it will affect both orientations. However, I have done the rest of the changes.
