### ISSUE TITLE
Confirm that API key is not saved with app (and not visible in Github!)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#39]
I tried uninstalling Boswell on my iPhone, then re-installed it.  When I did, the API key was already filled in.  Shouldn't it have been cleared out for a new install? Please confirm that it is cleared out.  I don't want to share my personal OpenAI API key with the world!

**Comment by bhautikpatoliya004** [comment]
I didn't save the API key on the device. If the user fresh installs the app then it's always blank. can you please test again with uninstall?

**Comment by bhautikpatoliya004** [comment]
If you add a key on openAI_APIKey.plist then key will already fill in otherwise not.
