### ISSUE TITLE
Add line feed after image

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#40]
When the "Create Image" option is selected, we need to have an extra line feed (Carriage Return) added after the image so that when the PDF is generated, it doesn't look wrong.  See attached for the issue.
![Screenshot 2023-04-24 at 5 03 06 PM](https://user-images.githubusercontent.com/694013/234116493-a4d32a35-f27a-4557-b2d5-f4c0a12fb80e.png)

**Comment by bhautikpatoliya004** [comment]
Fixed
