### ISSUE TITLE
Improve Boswell Setup Dialog

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#42]
The text at the top of the Boswell dialog box should read as follows:
Boswell (title centered at top in larger font)
I am going to help you write your own biography.  

Before we begin, please enter your date of birth below:
[can we make the date selector smaller: e.g. Month pop-up, Day pop-up, Year pop-up on a single line?]

If the user has already entered a birthdate, be sure to set the date to what was already entered!

If the user presses Cancel on this window, we need to figure out a solution where it asks questions without knowing how old you are!

**Comment by tedbarnett** [comment]
When the user does correctly enter a birthdate, make sure the text that appears starts with "So, you were 13 in [year when you were 13]." followed by that first paragraph ("xxxx was a major year in world history...")

**Comment by bhautikpatoliya004** [comment]
If the user cancels the dialogue means the user will start normal CHAT

**Comment by bhautikpatoliya004** [comment]
Done
