### ISSUE TITLE
Enable speech-to-text via Whisper (OpenAI)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#45]
Apple's Siri voice recognition seems fast enough, but doesn't do punctuation well.  Might be good to try the alternative: OpenAI's "Whisper" protocols.  We already have Eleven Labs as an option for text-to-speech.

- For testing purposes, add a menu switch for Whisper/Apple speech recognition.
- Build both Whisper and Apple speech recognition systems

Here's a working open-source app using Whisper on iOS:
https://github.com/Saik0s/Whisperboard

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I have added addsPunctuation (https://developer.apple.com/documentation/speech/sfspeechrecognitionrequest/3930023-addspunctuation?changes=late_1_2) on Speech request and Also, I have added elevenlabs option to the menu. Please test it and let me know. Still, do we need to add Whisper?

**Comment by tedbarnett** [comment]
I'd like to see if Whisper does a better job. I want to choose the best tech we can to make sure this works well.

**Comment by tedbarnett** [comment]
Since we are seeing many errors in the speech-to-text (from the user speech), I would still like to test using Whisper as a tool (as an alternative to Apple's own speech recognizer).  We will end up choosing one or the other, but would like to see how it looks.  If it's a nightmare to set up, let me know.
