### ISSUE TITLE
Background Photos & Font Update

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#48]
This might be tricky but will look awesome...

Boswell is an interviewing app, so it will need to be able to show photos to users.  This will help elicit more stories, and create content to populate an eventual "podcast" that we can make from the collected spoken rememberances of the user (or his mother or father or whoever).

To hint at this ability, I'd like the app to open with a photo, chosen at random from the user's "favorites" folder in Apple Photos (or we set up a local folder from which we draw the photos).  It should be zoomed in close enough on the image so that the iPhone's screen is filled from top-to-bottom and left-to-right.

That photo should, after a 2-second pause, fade into the background of the Boswell application.  It will become progressively more transparent (against a black background) until it is at 20%.  The buttons and textview appear "on top of" the background image.  See below...

![Opening Sequence Boswell](https://user-images.githubusercontent.com/694013/234167790-8929abef-1004-4157-b5a6-e980d4f26d11.png)

Every 3 minutes, the photo changes -- dissolving from one to the next without interrupting the UI.

Here's how I'd like our screen to look henceforth:

![image](https://user-images.githubusercontent.com/694013/234162602-70119ba9-fe20-4821-b4ae-d9a74341f32b.png)

And here is the font name (Lato) and size and hex color values:
![image](https://user-images.githubusercontent.com/694013/234163290-e3f345bc-943a-40b9-87f4-52db9fd7f773.png)

The Lato font is available here: https://www.latofonts.com/lato-free-fonts/

**Comment by tedbarnett** [comment]
Also notice: I got rid of the borderline around the textView area.  Not necessary.
If it's hard to just ask for a random Favorite photo, then go ahead and ask for a photo from the user's library and use that one.  We can figure the system out later.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I'm working on this task. But for now, you can check the background option in the menu. Using this menu user can select a picture for the background. I will finish it by tomorrow

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Can you please send me the menu and share icon that you used in the above image? I think this icon is looking good compared to what we already have in the app.

**Comment by tedbarnett** [comment]
Sure.  Here is a link to the "Uizard" prototyping service and the project that I made this demo in:  https://app.uizard.io/p/0256488d

I will research how to export their icon set.  I think they are standard in some way.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  Done

**Comment by tedbarnett** [comment]
Looks gorgeous.  I will need to improve the UI for this (explaining what it does) and will write a new Issue for future changes.
