### ISSUE TITLE
Fix Xcode Setup

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#50]
Every time I pull and run your Xcode, I have to change the team.  Can't we make this "automatically manage signing" so this is not necessary?

Also: can we change the bundle identifier to something more meaningful like "com.boswell.app"?  I am still fixing my Apple Developer account so I can add that app to my account (and add you as a collaborator).  I want this on TestFlight soon.

![Screenshot 2023-04-25 at 10 55 59 AM](https://user-images.githubusercontent.com/694013/234320994-ed3b336c-d912-42cc-8b20-c49fd61b7bea.png)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett For the run iOS app on my device, I need a profile that has my device UDID which is why I'm updating this team and profile settings. if you invite me to your Apple account then we can both use the same team to run the app.

**Comment by tedbarnett** [comment]
Okay. What Apple ID should I invite?
