### ISSUE TITLE
Simplify Mode Menu (only one ChatGPT option)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#51]
I'd like to change something I had asked for incorrectly.  The Pop-up Title Menu is working well, but I think it's too "nerdy" to see both ChatGPT models as options.  Most users don't know what ChatGPT-3.5 vs. ChatGPT-4, so I'd like to simplify as follows:

1. Add back the "ChatGPT-3.5/ChatGPT-4" option under the OpenAI API menu.  Ideally, this could be a simple pop-up menu with those two choices (rather than radio buttons).  The default should be ChatGPT-3.5 for now.  I was wrong to suggest removing this before!
2. Reduce the Pop-Up Title Menu to only these 3 options: Boswell, ChatGPT, and Create Image.  If the user selects ChatGPT, it will use the model already selected under the OpenAI API menu (see above).

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  Done

**Comment by tedbarnett** [comment]
Works great!  Minor issues remaining:
- The first time the app loads, the title reads "ChatGPT-4".  It should read "ChatGPT".
- The switching mode text (e.g. "switched to Create Image mode..") should be in a smaller font size (18 points?), and punctuated with a capitalized first letter and 3 periods at end (e.g. "Switched to 'Create Image' mode...")

**Comment by tedbarnett** [comment]
Fixed!
