### ISSUE TITLE
Simplify Record button

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#52]
I'd like to try making the UI looks "flatter" by making the Start Recording button just look like blue text on the screen (like a link) and a bit larger:

1) Replace button design with just a blue text link
2) Increase font size of text to 22 pts

Keep the text the same otherwise

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  little bit confused here because I see two descriptions for the record button (#48 , #52). So which one do I need to implement?

**Comment by tedbarnett** [comment]
Sorry about that.  Bad product manager!  You made a good guess.  I may later decide to remove the border around the button but I'm liking it for now...
