### ISSUE TITLE
Interview Audio Playback

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#58]
As a first-phase of generating a "Life Story" audio podcast from the Boswell interviews, can we try the following:

- Add a new menu item (after "Select Photos") labeled "Play back interview"
- When selected, a dialog box appears reading "Listen to the audio we have recorded from your Boswell Interviews so far...".  The dialog box should have a Cancel button and a Play/Pause button (or Play/Rewind/Pause or basic audio playback UI if available).

I mocked this up in the Uizard board ([link](https://app.uizard.io/p/0256488d)):

![image](https://user-images.githubusercontent.com/694013/234899778-28d66e6b-ddab-4844-b850-d4854f9cc22c.png)

**Comment by tedbarnett** [comment]
- When the user presses "Play", the complete audio of all of the user responses recorded while in the Boswell mode should play back through the current speaker.
- While playing audio, the Play button should switch to a "Pause" icon.  If Pause is pressed, the audio pauses at that point and the button returns to "Play" icon.  If pressed again, it continues to play.
- If STOP button (square) is pressed, audio stops and rewinds to the start
- If "X" (exit) button is pressed, audio stops and dialog box disappears

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I have reviewed the above details and designed the audio playback dialogue. but currently, we don't store the audio of the user speaking and AI response. so I'm thinking we just need to play speech using AVSpeechSynthesizer or ElevenLabs if the Boswell interview is available. The best option is to send interview history to ElevenLabs as a prompt they will return the audio and we will use this audio as a podcast. Another thing is we can't separate the voice of the user and the AI response if we use ElevenLabs or AVSpeechSynthesizer.

Please let me know your thoughts here.

**Comment by tedbarnett** [comment]
I'm afraid that won't work.  We want the actual audio of the user speaking stored and played.  I want to make an audio memory of my father, and don't want to hear a simulated version of his voice.  I realize this is a major issue (storing all that audio), but modern iPhones have plenty of storage.  Is there not a way to assemble a large .wav or .mp3 file from the audio that is received?  Is there no way to intercept the incoming audio from the user?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Done. Please check it and let me know your thoughts on it.

**Comment by tedbarnett** [comment]
SO AWESOME!!!
