### ISSUE TITLE
Boswell gets confused when first loaded

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#61]
When I first switch to Boswell mode and answered the first question ("Hello Ted, when..."), rather than ask me a follow-up question, the AI seemed to take MY role and explained my answer in another way.  It's like it thinks it needs to be the "user".  Not sure why this is yet.  Has something to do with the Boswell prompt.

Screenshot example below:
![IMG_5686](https://user-images.githubusercontent.com/694013/235232849-8720b66c-8c3b-4847-bc93-08df4a44386c.PNG)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett 
I have tried to reproduce this issue at my end but unfortunately, I'm not able to reproduce this issue.
Can you tell me which API model are you using? 

Right now we are using "Please refer to me as <name>. I want you to interview me about my life. Please use my name while taking interview. I want you to start by stating that when I was 13 years old, the year was <age> and briefly mention 3 major world events that occurred that year. Then stop, skip two single blank lines, and then ask me a question about my life when I was 13 years old. Wait for me to type in an answer then ask another question that encourages me to tell more about my life. Stop after you've asked each question to wait for me to answer. If I ever respond with the word QUIT, then stop the interviewing process and return to answering questions as ChatGPT would." prompt for Boswell mode.

Please let me know if any correction is required in the above prompt for Boswell.

**Comment by tedbarnett** [comment]
I will try to reliably reproduce this, but it is still happening.  I was using ChatGPT-3.5 at the time.  In this example screen below, I 1)started in ChatGPT mode and asked for 2 jokes, then 2) switched to Boswell mode (but had not set a username yet), only a birthdate.  The result was that Boswell gave itself the name "ChatGPT" and thought it was talking about itself.  Maybe this is a carryover from some prior state?  I will keep trying to reproduce this more clearly.

**Comment by tedbarnett** [comment]
![image](https://user-images.githubusercontent.com/694013/235469302-a4d51353-80e9-4a2a-80fe-afbba261963d.png)
