### ISSUE TITLE
Randomize Boswell first-prompt question

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#67]
To make the app more interesting to use (and demonstrate), let's change the first-prompt question by referencing a randomized year and focusing on cultural issues rather than world events.  You'll first need to calculate the year as follows: choose a random integer "user_age_for_question" between age 3 and the user's age 10 years ago (e.g. I was born in 1962 and am 60 years old now, so the range would be 3 - 50).   The "year_for_question" would be that year (e.g. if we picked age 10 for me, it would be 1972.

The new prompt should read as follows (not sure why there are two versions in Viewcontroller+Menu.swift!)

let content = firstname != "" ? "Please refer to me as \(firstname). I want you to interview me about my life. Please use my name while conducting the interview. I want you to start by stating that when I was \(user_age_for_question) years old, the year was \(year_for_question) and briefly mention 3 major U.S. cultural events that occurred that year. Then stop, skip two single blank lines, and then ask me a question about my life when I was \(user_age_for_question). Wait for me to type in an answer then ask another question that encourages me to tell more about my life. Stop after you've asked each question to wait for me to answer. If I ever respond with the word QUIT, then stop the interviewing process and return to answering questions as ChatGPT would." : "Please refer to me as \(firstname). I want you to interview me about my life. Please use my name while conducting the interview. I want you to start by stating that when I was \(user_age_for_question) years old, the year was \(year_for_question) and briefly mention 3 major U.S. cultural events that occurred that year. Then stop, skip two single blank lines, and then ask me a question about my life when I was \(user_age_for_question). Wait for me to type in an answer then ask another question that encourages me to tell more about my life. Stop after you've asked each question to wait for me to answer. If I ever respond with the word QUIT, then stop the interviewing process and return to answering questions as ChatGPT would."

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I understood the logic of calculating years but I have one question what if the user selects 2015 as the birth year? if the user selects 2015 that means he/she is 8 years old now. 8-10 = -2, so the range is (3, -2) I think it's not a valid range. so in that case we need to add validation when the user selects birthdate. We need to allow this user only those 15 years old. please let me know your thoughts on it.

**Comment by tedbarnett** [comment]
An excellent point.  Let's make the cut-off age 15 (i.e. you must be at least 16 or older to use Boswell).
