### ISSUE TITLE
Add Boswell chat conversation to user's chat history on ChatGPT

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#7]
Currently, the conversations completed in this application are not automatically added to the user's chat history on the web client for ChatGPT (https://chat.openai.com/chat).  It is possible to do an API call to implement this.

**Comment by tedbarnett** [comment]
I thought I had read this was do-able with the API.  Maybe have to execute a "completion" call?  https://platform.openai.com/docs/api-reference/completions

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I have tested completion API but it's not for saving history to the web client. I have searched through Chat GPT. Basically, GPT doesn't have an API to save history on the web client. They are suggesting saving history on your own database.
