### ISSUE TITLE
Return to prior mode when returning from closed app

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#97]
If I am in Boswell or Create Image mode and close the app (swipe up) and then re-open it, it always re-opens in ChatGPT mode.  This is incorrect.

The app should always re-open in whatever state it was when closed.  If it was in Boswell mode, return to where it was.  Same for Create Image.  And re-load the chat history related to that mode.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  Right now we are not storing chat history on the device so it's not possible to reload chat history after closing the app. If we want this reload chat history feature then we need to store each prompt in CoreData. That way we can get the chat history in future. CoreData is a local databas
